### ISSUE TITLE
C++ 语言面向对象文档出现错误

### ISSUE THREAD

**Issue by welann** [SAST-skill-docers/sast-skill-docs#17]
https://docs.net9.org/languages/c-oop/reference-copy/#:~:text=%E4%BE%8B%E5%AD%90-,%E7%A6%81%E7%94%A8%E8%BF%94%E5%9B%9E%E5%80%BC%E4%BC%98%E5%8C%96,-1%0A%202%0A%203

这个例子应该是搞错了，并没有加上移动构造函数

**Comment by c7w** [comment]
收到您的反馈. 

在类的定义中确实忘记了重载移动构造函数使其输出 Debug 信息，这是我们文档编写组与审核组的纰漏，在此请求您的谅解.

这里倘若重载了移动构造函数，且关闭了返回值优化的前提之下，在 return 返回右值的前提之下，18->23行的 return 是会直接调用移动构造函数将返回值返回的.

近期将会对文档该处进行更新并重新进行审核，为您造成的不便请您谅解！

**Comment by welann** [comment]
> 为您造成的不便请您谅解！

你们做的这些东西很棒，已经帮了我大忙啦😘加油

**Comment by zhaochenyang20** [comment]
原作者出来谢罪了，Orz，你提的地方是去年的 oop 作业，我写的报告
当时是为了方便自己理解来着

**Comment by welann** [comment]
> 原作者出来谢罪了，Orz，你提的地方是去年的 oop 作业，我写的报告
> 当时是为了方便自己理解来着

能把自己总结的东西分享出来就已经很好了😘respect
看大部头看的头疼，看这份文档就感觉像是喝了冰可乐一样舒服（

**Comment by c7w** [comment]
文档已更新，原缓存将在 1h 内刷新.
感谢您的支持.
