### ISSUE TITLE
为 js 异步部分提一个例子

### ISSUE THREAD

**Issue by zhaochenyang20** [SAST-skill-docers/sast-skill-docs#20]
个人感觉在[[引入 Promise 对象](https://docs.net9.org/languages/javascript/async/#promise)](https://docs.net9.org/languages/javascript/async/#promise)的时候跳跃比较大，我没能都明白

自己来写一点引入的内容，参考[[廖雪峰的博客](https://www.liaoxuefeng.com/wiki/1022910821149312/1023024413276544)](https://www.liaoxuefeng.com/wiki/1022910821149312/1023024413276544)

Promise 对象的核心思想是每一个异步任务返回一个 Promise 对象，该对象有一个 then 方法，允许指定回调函数。

我们先看一个最简单的 Promise 例子：生成一个 0~2 之间的随机数，如果小于 1，则等待一段时间后返回成功，否则返回失败：

```javascript
function test(resolve, reject) {
    var timeOut = Math.random() * 2;
    log('set timeout to: ' + timeOut + ' seconds.');
    setTimeout(function () {
        if (timeOut < 1) {
            log('call resolve()...');
            resolve('200 OK');
        }
        // branch A
        else {
            log('call reject()...');
            reject('timeout in ' + timeOut + ' seconds.');
        }
        // branch B
    }, timeOut * 1000);
}
```

这个`test()`函数称为执行函数，具有有两个参数。

这两个参数都是函数，根据 timeout 方法，调用 `resolve('200 OK')` 或者调用 `reject('timeout in ' + timeOut + ' seconds.')`
可以看出，`test()` 函数只关心自身的逻辑，并不关心具体的 `resolve` 和 `reject` 将如何处理结果。

有了执行函数，我们就可以用一个 Promise 对象来执行它，并在将来某个时刻获得成功或失败的结果：

```javascript
var p1 = new Promise(test);
var p2 = p1.then(function (result) {
    console.log('success: ' + result);
});
var p3 = p2.catch(function (reason) {
    console.log('failed: ' + reason);
});
```

变量  p1 是一个 Promise 对象，它负责执行 test 函数。由于 test 函数在内部是异步执行的，当 test 函数进入 branch A 并且执行 resolve 语句时（或者说执行成功时），我们告诉 Promise 对象：

```javascript
// if test enter branch A
p1.then(function (result) {
    console.log('right: ' + result);
});
```

当 `test` 函数进入 branch B 并且执行 reject 语句（也即执行失败）时，我们告诉 Promise 对象：

```javascript
// if test enter branch B
p2.catch(function (reason) {
    console.log('wrong: ' + reason);
});
```

Promise 对象可以串联起来，所以上述代码可以简化为：

```javascript
new Promise(test).then(function (result) {
    console.log('right: ' + result);
}).catch(function (reason) {
    console.log('wrong: ' + reason);
});
```

连在一起的话，就是这个样子：

```javascript
new Promise(function (resolve, reject) {
    log('start new Promise...');
    var timeOut = Math.random() * 2;
    log('set timeout to: ' + timeOut + ' seconds.');
    setTimeout(function () {
        if (timeOut < 1) {
            log('call resolve()...');
            resolve('200 OK');
        }
        else {
            log('call reject()...');
            reject('timeout in ' + timeOut + ' seconds.');
        }
    }, timeOut * 1000);
}).then(function (r) {
    log('Done: ' + r);
}).catch(function (reason) {
    log('Failed: ' + reason);
});

```

可见Promise最大的好处是在异步执行的流程中，把执行代码和处理结果的代码清晰地分离了：

![](https://www.liaoxuefeng.com/files/attachments/1027242914217888/l)

**Comment by c7w** [comment]
欢迎直接 fork 下来本项目编辑后提交 Pull Request...
详见《编辑者须知》中的有关条目.
