### ISSUE TITLE
疑似错误

### ISSUE THREAD

**Issue by momona06** [SAST-skill-docers/sast-skill-docs#44]
此处JavaScript似乎是TypeScript？
源自编程语言->TypeScript语言基础->TypeScript的函数
<img width="702" alt="截屏2023-03-08 19 57 21" src="https://user-images.githubusercontent.com/93273462/223707448-8e0fbd2f-b0ec-473e-b61c-9e42a987d37b.png">

**Comment by abmfy** [comment]
应该没有错误，因为这里说的是「运行时」的行为，TS 只是将代码编译为 JS 代码，之后在作为 JS 代码运行时就不会再进行任何检查了
