### ISSUE TITLE
希望将课程指引从资源链接中独立出来

### ISSUE THREAD

**Issue by werkeytom** [SAST-skill-docers/sast-skill-docs#7]
我认为docs9的一个重要价值在于能简洁地、高质量地、系统地、有针对性地为贵系学生提供基本知识与技能的引导，其中课程指引是最有需要、最能彰显价值主张的部分。同学们通过课程指引页面查阅需要了解的技能资料与文档，更好的完成课程内容并学习到不止于课程的知识。

在现在的页面引导下，资源链接排在各种专门技能/知识介绍的前面，其下包含课程指引、书目推荐与外部链接。从布局逻辑上，很难理解资源链接何以排在各种“干货”之前。从用户交互上，我每次打开网页都难以直观找到课程指引位于哪一部分。

建议将课程指引页面直接独立为一个tab，取代目前资源链接的部分，方便用户查阅。未来也可以在该页面下继续集成关于课程的针对性引导内容，可扩展性良好。

同时资源链接的tab可以移至最后，用来放置各类外部资源，如博客、网站、工具、书目推荐、视频课程等。

**Comment by c7w** [comment]
感谢建议，已更改，将在下次部署时更新
